exports.action     = require('./lib/action')
exports.also       = require('./lib/also')
exports.error      = require('./lib/error')
exports.handle     = require('./lib/handle')
exports.logError   = require('./lib/logError')
exports.onSuccess  = require('./lib/onSuccess')
exports.sideEffect = require('./lib/sideEffect')
